name: Contracts CI
on:
  pull_request:
    paths:
      - "contracts/**"
      - "scripts/**"
      - "tests/contracts/**"
      - ".github/workflows/contracts-ci.yml"
  push:
    branches: [ main ]
    paths:
      - "contracts/**"
      - "scripts/**"
      - "tests/contracts/**"
jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Validate contracts
        run: |
          python scripts/validate.py
          python scripts/validate_cross_contracts.py
          python scripts/validate_dependencies.py
      - name: Run tests
        run: pytest -q
