---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: contracts-validate
        name: contracts-validate
        entry: python scripts/validate.py
        language: system
        pass_filenames: false
        files: ^contracts/.*\.schema\.json$
      - id: contracts-tests
        name: contracts-tests
        entry: pytest -q
        language: system
        pass_filenames: false
        files: ^(contracts/|tests/contracts/)
      - id: block-vector-files
        name: block-vector-files
        entry: python tools/block_vector_files.py
        language: system
        pass_filenames: true
        files: ^(\.vector/|lichen-chunker/index/)
