#!/usr/bin/env python3
"""
Pre-commit hook to block vector/index files from being committed.

This prevents accidental commits of large generated index files that should
not be stored in version control.
"""

import sys
import re
from pathlib import Path


BLOCKED_PATTERNS = [
    r'^\.vector/',
    r'^lichen-chunker/index/',
    r'\.faiss$',
    r'\.index$',
]

BLOCKED_MESSAGE = """
❌ BLOCKED: Vector/index files cannot be committed

The following files are generated artifacts and should not be in version control:
"""


def main():
    """Check if any provided files match blocked patterns."""
    if len(sys.argv) < 2:
        sys.exit(0)  # No files to check
    
    blocked_files = []
    
    for file_path in sys.argv[1:]:
        for pattern in BLOCKED_PATTERNS:
            if re.match(pattern, file_path):
                blocked_files.append(file_path)
                break
    
    if blocked_files:
        print(BLOCKED_MESSAGE)
        for file_path in blocked_files:
            print(f"  - {file_path}")
        print("\nThese files are automatically generated by the reindex pipeline.")
        print("Add them to .gitignore or remove them from staging.")
        print("\nTo fix: git reset HEAD <file>...")
        sys.exit(1)
    
    sys.exit(0)


if __name__ == "__main__":
    main()