/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Root schema for validating all contract files in /contracts (rooms, gates, services, orchestrator).
 */
export interface LichenProtocolContracts {
  /**
   * Unique identifier for the contract, e.g. room/entry, gate/integrity_linter.
   */
  id: string;
  /**
   * Contract category.
   */
  type: "room" | "gate" | "service" | "orchestrator";
  /**
   * Plain-language description of what this contract governs.
   */
  description: string;
  /**
   * Expected input signals or payloads.
   */
  inputs: {
    name: string;
    type: string;
    required?: boolean;
    description?: string;
    [k: string]: unknown;
  }[];
  /**
   * Expected output signals or payloads.
   */
  outputs: {
    name: string;
    type: string;
    description?: string;
    [k: string]: unknown;
  }[];
  /**
   * Optional contract-specific settings (e.g., diagnostics.enabled).
   */
  options?: {
    [k: string]: unknown;
  };
}
