/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DiagnosticsServiceContract {
  service_id: "diagnostics_service";
  title: string;
  version: string;
  purpose: string;
  /**
   * @minItems 1
   */
  signals: [string, ...string[]];
  defaults: {
    capture_on_room_entry: boolean;
    capture_on_room_exit: boolean;
    persist_to_memory: boolean;
    toggle_supported: boolean;
  };
  inputs: {
    session_state_ref: string;
    room_id: string;
    raw_text?: string;
    metadata?: {
      [k: string]: unknown;
    };
  };
  outputs: {
    diagnostic_snapshot: {
      tones: string[];
      residues: string[];
      readiness: "ready" | "hesitant" | "reluctant" | "unknown";
      joy_sample?: "present" | "absent" | null;
    };
    timestamp: string;
  };
  persistence: {
    write_path: string;
    upsert_strategy: "append_with_timestamp" | "replace" | "merge";
    retention_days: number;
    prune_on_expiry: boolean;
  };
  metrics_hooks: {
    /**
     * Implementation-defined hook identifier or path
     */
    drift_events?: string;
    /**
     * Implementation-defined hook identifier or path
     */
    signal_frequency?: string;
    [k: string]: unknown;
  };
  safety: {
    pii_policy: string;
    allow_disable_per_room: boolean;
  };
}
