/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GateFoundationStonesAlignmentFilter {
  gate_id: "stones_alignment_filter";
  title: string;
  version: string;
  purpose: string;
  /**
   * @minItems 1
   */
  criteria: [string, ...string[]];
  inputs: {
    candidate_text: string;
  };
  outputs: {
    stones_pass: boolean;
    violated_stones: string[];
  };
  on_failure: {
    action: "regenerate";
    max_attempts: number;
    fallback: "refusal_library";
  };
}
