/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GateCoherenceGate {
  gate_id: "coherence_gate";
  title: string;
  version: string;
  purpose: string;
  checks: {
    consistency_required: boolean;
    drift_detection_enabled: boolean;
  };
  inputs: {
    candidate_text: string;
    session_state_ref: string;
  };
  outputs: {
    coherence_pass: boolean;
    drift_events: {
      reason: string;
      location: string;
    }[];
  };
  on_failure: {
    action: "refusal_library";
    refusal_style: ("not_now" | "not_like_this")[];
    offer_alternative: boolean;
  };
}
