/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GateIntegrityLinter {
  gate_id: "integrity_linter";
  title: string;
  version: string;
  purpose: string;
  checks: {
    prohibited: string[];
    required_alignment: string[];
  };
  inputs: {
    raw_text: string;
  };
  outputs: {
    lint_pass: boolean;
    issues: {
      rule: string;
      reason: string;
    }[];
  };
  on_failure: {
    action: "regenerate";
    max_attempts: number;
    fallback: "refusal_library";
  };
}
