/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GatePlainLanguageRewriter {
  gate_id: "plain_language_rewriter";
  title: string;
  version: string;
  purpose: string;
  rules: {
    forbid: string[];
    enforce: string[];
  };
  inputs: {
    candidate_text: string;
  };
  outputs: {
    rewritten_text: string;
    changes_made: string[];
  };
  on_failure: {
    action: "return_original";
    note: string;
  };
}
