/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GateRefusalLibrary {
  gate_id: "refusal_library";
  title: string;
  version: string;
  purpose: string;
  refusal_modes: {
    not_now: string;
    not_like_this: string;
    not_us: string;
  };
  inputs: {
    failure_reason: string;
  };
  outputs: {
    refusal_text: string;
    refusal_mode: "not_now" | "not_like_this" | "not_us";
  };
  notes?: string;
}
