/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PRARoomContract {
  room_id: string;
  title: string;
  version: string;
  purpose: string;
  mini_walk_supported: boolean;
  completion_prompt_required: boolean;
  diagnostics_default: boolean;
  gate_profile: {
    chain: ("integrity_linter" | "plain_language_rewriter" | "stones_alignment_filter" | "coherence_gate")[];
    overrides?: {
      [k: string]: unknown;
    };
  };
  inputs: {
    payload?: {
      [k: string]: unknown;
    } | null;
    session_state_ref: string;
    [k: string]: unknown;
  };
  outputs: {
    display_text: string;
    next_action: string;
    pace_label?: "NOW" | "HOLD" | "LATER" | "SOFT_HOLD" | null;
    consent_status?: "granted" | "withheld" | "not_applicable" | null;
    diagnostic_summary?: {
      [k: string]: unknown;
    } | null;
    telemetry?: {
      [k: string]: unknown;
    } | null;
  };
}
